name: 🚀 Submission
description: Submit your project 💡
body:
 - type: input
   id: Project type 
   attributes:
     label: What kind of project path do you submit?
     placeholder: Early-warning system (Anomaly Detection)/ Visualization / Both
   validations:
     required: true
 - type: textarea
   id: Project description
   attributes:
     label: Project description
     description: Tell us what you build
   validations:
     required: true
 - type: input
   id: Streanlit link
   attributes:
     label: For visualization-type projects
     description: Insert Streamlit project URL
   validations:
     required: false
 - type: input
    id: source code
    attributes:
      label: Link to source code
    validations:
      required: false
 - type: textarea
   id: Instructions
   attributes:
     label: Instructions for the reviewers
     description: Add instructions for running your project here. The judges will use these to run your project.
   validations:
     required: true
 - type: textarea
   id: Background
   attributes:
     label: What made you decide to build this particular app?
     description: What inspired you?
   validations:
     required: false
 - type: textarea
   id: other information
   attributes:
     label: Any other information
   validations:
     required: false
 - To keep your sensitive data private please heat to this [Google form](https://docs.google.com/forms/d/e/1FAIpQLSecz9jV_bhVaC4zodhbD7QFqQYo_V9B8w9skJlLHOhI6WrWlw/viewform) to complete the submission.

