name: 🚀 Save Zakar Hackathon Submission
description: Submit your project
title: "Project name: "
body:
  - type: input
    attributes:
      value: |
        You are one step further to save the world!
  - type: input
    attributes:
      label: Project type
      description: Choose between an Early-warning system (Anomaly Detection)/ Visualization / Both
    validations:
      required: true
  - type: textarea
    attributes:
      label: Project description
      description: Tell us what you build
    validations:
      required: true
  - type: input
    attributes:
      label: Streamlit link
      description:  For visualization-type projects only.
    validations:
      required: false
  - type: input
    attributes:
      label: Source code
    validations:
      required: false
  - type: textarea
    attributes:
      label: Instructions for the reviewers
      description: Add instructions for running your project here. The judges will use these to run your project.
        validations:
      required: false
  - type: textarea
    attributes:
      label: What made you decide to build this particular app?
      description: Tell us What inspired you. 
        validations:
      required: false
  - type: textarea
    attributes:
      label: Other information
      description: Add any other information 
        validations:
      required: false
  - To keep your sensitive data private please heat to this [Google form](https://docs.google.com/forms/d/e/1FAIpQLSecz9jV_bhVaC4zodhbD7QFqQYo_V9B8w9skJlLHOhI6WrWlw/viewform) to complete the submission.
